version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: embalses-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: embalses
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
